(require 'yasnippet)
(setq yas/root-directory '("~/.emacs.d/vendor/yasnippet/snippets" "~/.emacs.d/snippets"))
(yas/initialize)
(setq yas/prompt-functions '(yas/dropdown-prompt yas/ido-prompt yas/x-prompt))
(setq yas/wrap-around-region 'cua)
